### ISSUE TITLE
Provide toEcho example

### ISSUE THREAD

**Issue by ghost** [sitrunlab/learn-kahlan#5]
Later perhaps the docs could be dynamically generated based on this entire rig. Practical? Not really. Would it be awesome? Totally.

**Comment by samsonasik** [comment]
Hi @jhabdas ,

Thank you for the suggestion. I've created PR https://github.com/sitrunlab/learn-kahlan/pull/6 for it. Please verify if that works for you.

I'm not sure with "dynamically generated" you meant.
