### ISSUE TITLE
Provide example of importing a namespaced function

### ISSUE THREAD

**Issue by ghost** [sitrunlab/learn-kahlan#7]
Importing namespaced functions was made available with https://github.com/php/php-src/pull/526. It would be super helpful to provide an example not using classes, but using `use function` instead.

**Comment by samsonasik** [comment]
Hi @jhabdas , 

Thank you for the suggestion. `use function` is do-able, the only drawback is `use function` is not patch-able by kahlan.

Please provide PR if you have suggested example of using it.

**Comment by samsonasik** [comment]
see issue https://github.com/kahlan/kahlan/issues/232

**Comment by ghost** [comment]
> Please provide PR if you have suggested example of using it.

As soon as I can grok how to do it, I will gladly. 😄 Unlike the above issue, I'm not using an autoloader. Here's what I'm trying to accomplish:

```
├── spec
│   └── hyperdrive.spec.php
├── src
│   ├── hyperdrive.php
```

Where the contents of each file are like:

```php
namespace hyperdrive;

function enter_hyperspace( $dark_energy ) {
  echo "<script>{$dark_energy}</script>";
}
```

```php
namespace hyperdrive\spec;

use function hyperdrive\enter_hyperspace;

describe('hyperdrive', function () {
  describe('enter_hyperspace()', function () {
    it('echos an empty script given an empty string', function () {
      expect(
        enter_hyperspace('')
      )->toEcho('<script></script>');
    });
  });
});
```

Based [PHP: Using namespaces](http://php.net/manual/en/language.namespaces.basics.php) it seems like the above should be supported. But when I unleash the test runner I receive the following message:

    `Error` Code(0) with message "Call to undefined function hyperdrive\\enter_hyperspace()"

@samsonasik If you can point me in the right direction I will send up that PR.

**Comment by samsonasik** [comment]
You should can register the function under `files` under autoloader:

```javascript
     "autoload": {
         "psr-4": {
             "App\\": "src/"
        },
        "files": [
            "src/hyperdrive.php"
        ]
     },
```
after added, you can run:

```
composer dump-autoload
```

**Comment by ghost** [comment]
@samsonasik worked like a charm! 🥇 let me get my first test integrated into the [hyperdrive](https://github.com/comfusion/hyperdrive) with this beautiful library and I'll send up that PR afterwards. thank you kindly for your help.

**Comment by ghost** [comment]
As promised: https://github.com/sitrunlab/learn-kahlan/pull/9/
