### ISSUE TITLE
First time user experience

### ISSUE THREAD

**Issue by ghost** [sitrunlab/learn-kahlan#8]
Following the installation instructions I ran cloned this repo and ran:

```shell
composer install
bin/kahlan --coverage=4
```

And received:

```shell
ERROR: PHPDBG SAPI has not been detected and Xdebug is not installed, code coverage can't be used.
```

It's obvious to me I may need to update my environment further to run the tests successfully with code coverage. But I'm opening this since those steps are not covered in the installation steps provided in the `README`.

**Potential remediations**

- Provide containerized setup using Docker
- Or simply suggest the additional steps needed to run the bin scripts

**Comment by samsonasik** [comment]
Hi @jhabdas ,

Thank you for trying it. It may needs to add `ext-xdebug:*` to composer.json's require-dev. I don't have docker experience, if you could write its Docker script, would be awesome, PR maybe?

**Comment by ghost** [comment]
> [I]f you could write its Docker script, would be awesome, PR maybe?

Perhaps later. I noticed there's a Docker rig in the `kahlan` org which may make a good base image for such a thing. I do [have](https://habd.as/swarm-clusters-digital-ocean/) [some](https://habd.as/chat-applications-redis-docker-go/) [experience](https://habd.as/simple-websites-jekyll-docker/) Dockerizing things. But before I could help with that I need to get this puppy running first so I can sub that pull I promised showing the procedural approach to testing with Kahlan using nothing but namespaces and functions. 😃

**Comment by samsonasik** [comment]
Awesome, Thank you. I've added `ext-xdebug` and `ext-phpdbg` to composer.json's suggest. https://github.com/sitrunlab/learn-kahlan/commit/e5ca348c056187c26e3e4545bf928b232c6c5f5f

**Comment by ghost** [comment]
No problem. I updated my package manifest to add `ext-debug` but it looks like I'd need to install a language extension. I received the following message:

```
The requested PHP extension ext-xdebug * is missing from your system. Install or enable PHP's xdebug extension.
```

I'm going to get a hold of that and install it so I can send up my pull, and close this issue since it's solved from my end.

**Comment by ghost** [comment]
`brew install ext-xdebug` doesn't install it. Wishful thinking. How does one install a PHP extension? I tried searching the error message and got a ton of irrelevant results. 😝

**Comment by ghost** [comment]
Never mind. I think I figured it out. Did a `php -v` to grab the version number and am doing a `brew install php70-xdebug`. If you see a pull request after this it worked. Hehe.

**Comment by ghost** [comment]
Score!

**Comment by samsonasik** [comment]
awesome :+1:
